// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoT8BLW07j68VLWFBYAjBP9OXJKAL483s',
    appId: '1:1035507828482:web:8f412d92a7b3ee8c7ce41b',
    messagingSenderId: '1035507828482',
    projectId: 'mynotes-hakor-app-d9140',
    authDomain: 'mynotes-hakor-app-d9140.firebaseapp.com',
    storageBucket: 'mynotes-hakor-app-d9140.appspot.com',
    measurementId: 'G-397DH8V3Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMT67DoV4egse-GhyyHKkdRQYGqnH9XSI',
    appId: '1:1035507828482:android:237f96068400db1e7ce41b',
    messagingSenderId: '1035507828482',
    projectId: 'mynotes-hakor-app-d9140',
    storageBucket: 'mynotes-hakor-app-d9140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPLepjGwUeBhxDQrIUP5uMfE7I3ALATM',
    appId: '1:1035507828482:ios:b06d197ed766adf97ce41b',
    messagingSenderId: '1035507828482',
    projectId: 'mynotes-hakor-app-d9140',
    storageBucket: 'mynotes-hakor-app-d9140.appspot.com',
    iosClientId: '1035507828482-brhq6vs113j4uahjd50nt83kf9oickes.apps.googleusercontent.com',
    iosBundleId: 'sl.hakorappsbird.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPLepjGwUeBhxDQrIUP5uMfE7I3ALATM',
    appId: '1:1035507828482:ios:fa2cb2a3306a393f7ce41b',
    messagingSenderId: '1035507828482',
    projectId: 'mynotes-hakor-app-d9140',
    storageBucket: 'mynotes-hakor-app-d9140.appspot.com',
    iosClientId: '1035507828482-8o2mrts6cheqhe1p0kr6pntf931e3avi.apps.googleusercontent.com',
    iosBundleId: 'sl.hakorappsbird.mynotes.RunnerTests',
  );
}
